### PR TITLE
updated g-drive (retry)

### PR DESCRIPTION
**Pull request by Kirs10-Riley**

### CODE REVIEW

**Comment by kbuzard** [comment]
@Kirs10-Riley : The way this pull request is set up is creating conflicts. I moved the G-Drive.Rmd / pdf files into the heterogeneity folder, but this seems like maybe it's putting them back in the  main folder but also modifying what's in the heterogeneity folder (where I want this file to live permanently). Can you troubleshoot?

**Comment by kbuzard** [comment]
It's still saying there are conflicts. Here's my best guess as to what's going on (tell me if this seems right): this kind of conflict would result if you did not update your version of the repo with the changes I made (essentially, moving the file into the heterogeneity folder) before you started making changes.

**Comment by Kirs10-Riley** [comment]
Yes! it will not let me fetch upstream now without creating a pull request. Is there a way I can fetch without creating a pull request?

**Comment by kbuzard** [comment]
> Yes! it will not let me fetch upstream now without creating a pull request. Is there a way I can fetch without creating a pull request?

I just downloaded the .Rmd file and compiled it on my local machine, then pushed the changes to the repo. Let's try this as a way to get things straightened out for you:
1. Check what's on Github now (you can look at the file online at https://github.com/kbuzard/labs/blob/master/heterogeneity/G-Drive.pdf since you can't fetch right now)
2. If this looks right, then
    - Delete the pull request
    - Then we need to get the files on your local machine back in the state they were before you started modifying them.
       - At the command line, I would use git reset. I'm not sure how you can do this if you're using Github Desktop; I can help you troubleshoot if you're not sure.
    - Once all these changes you made are gone, you can then fetch/pull to get the new commits that you didn't have before

**Comment by Kirs10-Riley** [comment]
I use the web browser version and I cannot figure out how to reset it. I looked it up but the only one I could find is to delete the fork and create a new one.

**Comment by kbuzard** [comment]
@Kirs10-Riley I think your options then are to delete and make the new fork, use Github Desktop, or the command line (where I can tell you exactly what to do). Switching to Github Desktop or the command line will be more functional long term--there is such limited functionality on the website...

**Pull request closed without merging**
